import Head from "next/head";
//Componets
import { MovieInfo, MovieList } from "@components/index";
//Layout
import { Layout } from "@layout/Layout";
//Service
import { getMovieDetail, getSimilarMovies } from "services";

const MovieDetail = ({ movieDetail, similarMovies }) => {
  return (
    <>
      <Head>
        <title>{movieDetail.title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MovieInfo movie={movieDetail} />
      <MovieList movies={similarMovies} title={"Títulos Similares"} />
    </>
  );
};

export default MovieDetail;

MovieDetail.getLayout = function getLayout(page) {
  return <Layout>{page}</Layout>;
};

export const getServerSideProps = async (context) => {
  const { params } = context;
  const movieDetail = await getMovieDetail(params.id);
  const similarMovies = await getSimilarMovies(params.id);

  return {
    props: {
      movieDetail,
      similarMovies,
    },
  };
};
