import { useContext, useEffect } from "react";
import { useUser } from "@auth0/nextjs-auth0/client";
import { useRouter } from "next/router";
import Head from "next/head";
import MoviesContext from "context/MoviesContext";
//Components
import { MovieList } from "@components/index";
import { SearchResults } from "@components/index";
//Services
import {
  getPopularMovies,
  getTopRatedMovies,
  getUpcomingMovies,
  setDocumentFirstLog,
} from "services";

export default function Home({
  popularMovies,
  topRatedMovies,
  upcomingMovies,
}) {
  const { searchResults } = useContext(MoviesContext);
  const { user } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (!user) {
      router.replace("/login");
    } else {
      setDocumentFirstLog(user.email);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        {user && (
          <>
            {searchResults.length ? (
              <SearchResults />
            ) : (
              <>
                <MovieList title="Peliculas Populares" movies={popularMovies} />
                <MovieList title="Mejores Puntuadas" movies={topRatedMovies} />
                <MovieList title="Proximamente" movies={upcomingMovies} />
              </>
            )}
          </>
        )}
      </div>
    </>
  );
}

export async function getServerSideProps() {
  const popularMovies = await getPopularMovies();
  const topRatedMovies = await getTopRatedMovies();
  const upcomingMovies = await getUpcomingMovies();

  return {
    props: { popularMovies, topRatedMovies, upcomingMovies },
  };
}
